CC=gcc



ex_compile: ex_compile.c
	gcc -o ex_compile ex_compile.c -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/glib/2.64.1_1/include -I/usr/local/Cellar/glib/2.64.1_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.1_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include -L/usr/local/Cellar/glib/2.64.1_1/lib -L/usr/local/opt/gettext/lib -lgobject-2.0 -lglib-2.0 -lintl